version: '3.9'

services:

  # --- CAPA DE ENTRADA (REVERSE PROXY Y SSL) ---

  nginx:
    image: ghcr.io/ingsisg10/snippet-infrastructure:latest
    container_name: "reverse-proxy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy-net
      - auth-net
      - shared_network
    depends_on:
      - auth-service
      - snippet-service

  certbot:
    image: certbot/certbot
    container_name: "certbot"
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    command: >
      sh -c "while true; do certbot renew --quiet --webroot --webroot-path=/var/www/certbot; sleep 12h; done"
    networks:
      - proxy-net

#  certbot:
#    image: certbot/certbot
#    container_name: "certbot"
#    restart: "no"
#    volumes:
#      - ./nginx/ssl:/etc/letsencrypt
#      - ./nginx/www:/var/www/certbot
#    command: [ "tail", "-f", "/dev/null" ]  # Keep container alive but do nothing

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=grupo10ingsis
      - TOKEN=${DUCK_DNS_TOKEN}
    volumes:
      - ./duckdns:/config

  # --- STACK DE PRINTSCRIPT ---

  printscript-service:
    image: ghcr.io/ingsisg10/snippet-service:latest
    container_name: printscript-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
       - shared_network

  # --- STACK DE AUTENTICACIÓN ---

  auth-service:
    image: ghcr.io/ingsisg10/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${AUTH_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_DB_PASSWORD}
    depends_on:
      - auth-db
    networks:
      - auth-net
      - shared_network

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - auth-net
      - shared_network

  # --- STACK DE SNIPPETS Y ASSETS ---

  snippet-service:
    image: ghcr.io/ingsisg10/snippet-service:latest
    container_name: snippet-service
    restart: unless-stopped
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME:-snippet_db}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRINTSCRIPT_SERVICE_URL: http://printscript-service:8080
      ASSET_SERVICE_URL: http://asset-service:8080
      AUTH_SERVICE_URL: http://auth-service:8081
      AUTH_SERVER_URI: dev-rhvn1b43rtt1hdap.us.auth0.com/
      AUTH0_AUDIENCE: https://my-api-identifier
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      - snippet-db
      - asset-service
    networks:
      - shared_network
      - auth-net

  snippet-db:
    container_name: snippet_db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${SNIPPET_DB_USER}
      - POSTGRES_PASSWORD=${SNIPPET_DB_PASSWORD}
      - POSTGRES_DB=${SNIPPET_DB_NAME}
    volumes:
      - snippet-data:/var/lib/postgresql/data
    networks:
      - shared_network

  asset-service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    container_name: asset-service
    restart: unless-stopped
    environment:
      - AZURE_HOST=http://azurite
      - NEW_RELIC_APP_NAME="asset-service"
      - NEW_RELIC_AGENT_ENABLED=false
    depends_on:
      - azurite
    networks:
      - shared_network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: always
    volumes:
      - blob:/workspace
    networks:
      - shared_network

# --- DEFINICIÓN DE REDES Y VOLÚMENES ---

volumes:
  auth-data:
  snippet-data:
  blob:

networks:
  proxy-net:
    driver: bridge
  auth-net:
    driver: bridge
  shared_network:
    driver: bridge
