# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy the Nginx configuration file
COPY nginx-proxy-manager/nginx.conf /etc/nginx/nginx.conf

# Copy the static files
COPY nginx/static /usr/share/nginx/html

# Expose port 80
EXPOSE 80
EXPOSE 443
