# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy the Nginx configuration file
COPY nginx/conf.d/nginx.conf /etc/nginx/nginx.conf

# Copy the static files
COPY nginx/static /usr/share/nginx/html

# Copy the SSL certificates
COPY nginx/certs /etc/letsencrypt

# Expose port 80
EXPOSE 80

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
