# Usa la imagen oficial de Nginx
FROM nginx:latest

# Elimina la configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copia la configuración personalizada de Nginx
COPY nginx/conf/nginx.conf /etc/nginx/conf.d/default.conf

# Copia el script de punto de entrada y dale permisos de ejecución
COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Instala openssl para poder generar el certificado dummy
RUN apt-get update && apt-get install -y openssl

# Define el punto de entrada del contenedor
ENTRYPOINT ["/entrypoint.sh"]

# El comando por defecto que ejecutará el entrypoint
CMD ["nginx", "-g", "daemon off;"]